-- STH M1-006: Idempotent registry-derived reference seed data.
BEGIN;
INSERT INTO reference.content_state (code) VALUES ('BUILDING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.content_state (code) VALUES ('VALIDATING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.content_state (code) VALUES ('READY') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.content_state (code) VALUES ('BLOCKED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.content_state (code) VALUES ('FAILED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.content_state (code) VALUES ('STALE') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.content_state (code) VALUES ('INVALIDATED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.content_state (code) VALUES ('ARCHIVED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.publication_state (code) VALUES ('NEVER_PUBLISHED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.publication_state (code) VALUES ('STAGED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.publication_state (code) VALUES ('PUBLISHING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.publication_state (code) VALUES ('PUBLISHED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.publication_state (code) VALUES ('UNPUBLISHED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.publication_state (code) VALUES ('SUPERSEDED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.publication_state (code) VALUES ('ROLLED_BACK') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.publication_state (code) VALUES ('WITHDRAWN') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.health_state (code) VALUES ('CLEAN') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.health_state (code) VALUES ('DIRTY') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.health_state (code) VALUES ('STALE') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.health_state (code) VALUES ('BLOCKED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.job_state (code) VALUES ('QUEUED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.job_state (code) VALUES ('CLAIMED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.job_state (code) VALUES ('RUNNING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.job_state (code) VALUES ('RETRY_WAIT') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.job_state (code) VALUES ('BLOCKED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.job_state (code) VALUES ('STALE') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.job_state (code) VALUES ('SUCCEEDED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.job_state (code) VALUES ('FAILED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.job_state (code) VALUES ('CANCELLED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.job_state (code) VALUES ('NO_OP') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.release_state (code) VALUES ('DRAFT') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.release_state (code) VALUES ('ASSEMBLING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.release_state (code) VALUES ('GENERATION_READY') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.release_state (code) VALUES ('GENERATING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.release_state (code) VALUES ('VALIDATING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.release_state (code) VALUES ('STAGED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.release_state (code) VALUES ('APPROVED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.release_state (code) VALUES ('PUBLISHING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.release_state (code) VALUES ('PUBLISHED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.release_state (code) VALUES ('BLOCKED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.release_state (code) VALUES ('PARTIAL_FAILURE') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.release_state (code) VALUES ('ROLLING_BACK') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.release_state (code) VALUES ('ROLLED_BACK') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.release_state (code) VALUES ('CANCELLED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.qa_status (code) VALUES ('PENDING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.qa_status (code) VALUES ('PASS') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.qa_status (code) VALUES ('FAIL') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.qa_status (code) VALUES ('REVIEW_REQUIRED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.render_type (code) VALUES ('WEB') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.render_type (code) VALUES ('PDF') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.render_type (code) VALUES ('PRINT') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.render_type (code) VALUES ('MOBILE_PREVIEW') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.report_variant (code) VALUES ('AGENT') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.report_variant (code) VALUES ('SELLER') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.report_variant (code) VALUES ('PUBLIC') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.reason_code (code) VALUES ('KERNEL_TEST_TRANSITION') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.reason_code (code) VALUES ('TRANSITION_NOT_ALLOWED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.reason_code (code) VALUES ('GUARD_REJECTED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.reason_code (code) VALUES ('CALLER_NOT_AUTHORIZED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.reason_code (code) VALUES ('CONTRACT_VALIDATION_FAILED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.error_code (code) VALUES ('SERVICE_NOT_READY') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.error_code (code) VALUES ('CONTRACT_HASH_MISMATCH') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.error_code (code) VALUES ('REGISTRY_VALIDATION_FAILED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.error_code (code) VALUES ('IDEMPOTENCY_KEY_PAYLOAD_MISMATCH') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.error_code (code) VALUES ('TRANSITION_CONFLICT') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.error_code (code) VALUES ('UNAUTHORIZED_CALLER') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.event_type (code,version) VALUES ('COMMAND_ACCEPTED',1) ON CONFLICT (code) DO UPDATE SET version=EXCLUDED.version;
INSERT INTO reference.event_type (code,version) VALUES ('TRANSITION_APPLIED',1) ON CONFLICT (code) DO UPDATE SET version=EXCLUDED.version;
INSERT INTO reference.event_type (code,version) VALUES ('TRANSITION_REJECTED',1) ON CONFLICT (code) DO UPDATE SET version=EXCLUDED.version;
INSERT INTO reference.event_type (code,version) VALUES ('UNAUTHORIZED_TRANSITION_ATTEMPT',1) ON CONFLICT (code) DO UPDATE SET version=EXCLUDED.version;
INSERT INTO reference.event_type (code,version) VALUES ('GUARD_FAILED',1) ON CONFLICT (code) DO UPDATE SET version=EXCLUDED.version;
INSERT INTO reference.event_type (code,version) VALUES ('OUTBOX_DELIVERY_FAILED',1) ON CONFLICT (code) DO UPDATE SET version=EXCLUDED.version;
INSERT INTO reference.guard_id (code,description) VALUES ('ENTITY_EXISTS','read-only guard') ON CONFLICT (code) DO UPDATE SET description=EXCLUDED.description;
INSERT INTO reference.guard_id (code,description) VALUES ('EXPECTED_STATE_MATCHES','read-only guard') ON CONFLICT (code) DO UPDATE SET description=EXCLUDED.description;
INSERT INTO reference.guard_id (code,description) VALUES ('CALLER_AUTHORIZED','read-only guard') ON CONFLICT (code) DO UPDATE SET description=EXCLUDED.description;
INSERT INTO reference.data_classification (code) VALUES ('PUBLIC_DATA') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.data_classification (code) VALUES ('SELLER_DATA') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.data_classification (code) VALUES ('AGENT_INTERNAL') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.data_classification (code) VALUES ('OPERATIONS_INTERNAL') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.data_classification (code) VALUES ('SYSTEM_INTERNAL') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.data_classification (code) VALUES ('RESTRICTED') ON CONFLICT (code) DO NOTHING;
COMMIT;
