-- STH M2-003: additive snapshot-requirement reason codes.
BEGIN;
INSERT INTO reference.reason_code (code) VALUES ('PROPERTY_IDENTITY_UNRESOLVED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.reason_code (code) VALUES ('PROPERTY_QA_NOT_ACCEPTED') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.reason_code (code) VALUES ('GOVERNANCE_SCHEMA_MISSING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.reason_code (code) VALUES ('INTELLIGENCE_SCHEMA_MISSING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.reason_code (code) VALUES ('PROPERTY_IDENTITY_DEPENDENCY_MISSING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.reason_code (code) VALUES ('PARCEL_IDENTITY_DEPENDENCY_MISSING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.reason_code (code) VALUES ('OPTIONAL_REAR_ADJACENCY_MISSING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.reason_code (code) VALUES ('OPTIONAL_CORNER_STATUS_MISSING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.reason_code (code) VALUES ('OPTIONAL_CUL_DE_SAC_STATUS_MISSING') ON CONFLICT (code) DO NOTHING;
INSERT INTO reference.reason_code (code) VALUES ('OPTIONAL_VIEW_CLASSIFICATION_MISSING') ON CONFLICT (code) DO NOTHING;
COMMIT;
