INSERT INTO reference.reason_code(code) VALUES
 ('DEPENDENCY_NOT_CONSUMED'),
 ('DEPENDENCY_SEMANTICS_UNCHANGED'),
 ('VARIANT_NOT_AFFECTED'),
 ('INVALIDATING_CORRECTION'),
 ('REQUIRED_DEPENDENCY_BLOCKED'),
 ('CHANGE_CLASS_REVIEW_REQUIRED'),
 ('DEPENDENCY_SEMANTIC_CHANGE')
ON CONFLICT(code) DO NOTHING;

INSERT INTO reference.event_type(code) VALUES
 ('REPORT_IMPACT_EVALUATED'),
 ('REPORT_MARKED_DIRTY'),
 ('REPORT_BLOCKED_BY_DEPENDENCY'),
 ('REPORT_INVALIDATION_RECOMMENDED'),
 ('REPORT_REVIEW_REQUIRED')
ON CONFLICT(code) DO NOTHING;
