BEGIN;
INSERT INTO reference.reason_code(code) VALUES
 ('DEPENDENCY_NOT_CONSUMED'),
 ('DEPENDENCY_SEMANTICS_UNCHANGED'),
 ('VARIANT_NOT_AFFECTED'),
 ('INVALIDATING_CORRECTION'),
 ('REQUIRED_DEPENDENCY_BLOCKED'),
 ('CHANGE_CLASS_REVIEW_REQUIRED'),
 ('DEPENDENCY_SEMANTIC_CHANGE')
ON CONFLICT(code) DO NOTHING;

INSERT INTO reference.event_type(code, version) VALUES
 ('REPORT_IMPACT_EVALUATED', 1),
 ('REPORT_MARKED_DIRTY', 1),
 ('REPORT_BLOCKED_BY_DEPENDENCY', 1),
 ('REPORT_INVALIDATION_RECOMMENDED', 1),
 ('REPORT_REVIEW_REQUIRED', 1)
ON CONFLICT(code) DO UPDATE SET version=EXCLUDED.version;
COMMIT;
