INSERT INTO reference.reason_code(code) VALUES
 ('RELEASE_GENERATION_QUEUED'),
 ('TARGET_REPORT_MISSING'),
 ('TARGET_SEMANTIC_FINGERPRINT_MISSING'),
 ('TARGET_RENDER_MISSING'),
 ('TARGET_PRESENTATION_FINGERPRINT_MISSING'),
 ('RELEASE_STAGED'),
 ('RELEASE_APPROVED'),
 ('RELEASE_ITEM_PUBLISHING'),
 ('RELEASE_ITEM_PUBLISHED'),
 ('RELEASE_ITEM_PUBLICATION_FAILED'),
 ('RELEASE_ROLLBACK'),
 ('RELEASE_CANCELLED')
ON CONFLICT(code) DO NOTHING;
