INSERT INTO reference.reason_code(code) VALUES
 ('INCIDENT_DETECTED'),
 ('INCIDENT_AUTOMATIC_CONTAINMENT'),
 ('INCIDENT_RECOVERY_STARTED'),
 ('RECOVERY_COMMAND_REQUESTED'),
 ('RECOVERY_ACTION_FAILED'),
 ('INCIDENT_RECOVERED'),
 ('INCIDENT_CLOSED')
ON CONFLICT(code) DO NOTHING;
