INSERT INTO reference.reason_code(code) VALUES
 ('BACKUP_VERIFIED'),
 ('BACKUP_VERIFICATION_FAILED'),
 ('RESTORE_VERIFIED'),
 ('RESTORE_VERIFICATION_FAILED'),
 ('POST_RESTORE_PUBLICATION_FREEZE'),
 ('POST_RESTORE_FREEZE_RELEASED')
ON CONFLICT(code) DO NOTHING;
